# This workflow uses the Makefile to build the raytracer project
name: Build Raytracer

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libconfig++-dev ninja-build libsfml-dev

    - name: Build with Make
      shell: bash
      run: |
        make release

    - name: Run tests
      shell: bash
      run: |
        cd build && ctest --output-on-failure
